In [49]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine("sqlite:///../data/superstore.db")

print("Database connected successfully!")

Database connected successfully!

In [50]:
query = """
SELECT *
FROM sales
LIMIT 5;
"""

result = pd.read_sql(query, engine)

result

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,US-2023-103800,2023-01-03,2023-01-07,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512
1,2,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870
2,3,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717
3,4,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748
4,5,US-2023-141817,2023-01-05,2023-01-12,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,...,19143,East,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3,0.2,4.8840

In [51]:
columns = pd.read_sql("PRAGMA table_info(sales);", engine)

columns

    cid            name    type  notnull dflt_value  pk
0     0          Row ID  BIGINT        0       None   0
1     1        Order ID    TEXT        0       None   0
2     2      Order Date    TEXT        0       None   0
3     3       Ship Date    TEXT        0       None   0
4     4       Ship Mode    TEXT        0       None   0
5     5     Customer ID    TEXT        0       None   0
6     6   Customer Name    TEXT        0       None   0
7     7         Segment    TEXT        0       None   0
8     8  Country/Region    TEXT        0       None   0
9     9            City    TEXT        0       None   0
10   10  State/Province    TEXT        0       None   0
11   11     Postal Code    TEXT        0       None   0
12   12          Region    TEXT        0       None   0
13   13      Product ID    TEXT        0       None   0
14   14        Category    TEXT        0       None   0
15   15    Sub-Category    TEXT        0       None   0
16   16    Product Name    TEXT        0       None   0
17   17           Sales   FLOAT        0       None   0
18   18        Quantity  BIGINT        0       None   0
19   19        Discount   FLOAT        0       None   0
20   20          Profit   FLOAT        0       None   0

In [52]:
count = pd.read_sql(
    "select COUNT(*) AS total_rows FROM sales",
    engine
)

count

   total_rows
0       10194

In [53]:
query = """
SELECT "Order ID", "Customer Name", "Sales", "Profit"
FROM sales
LIMIT 10;
"""

result = pd.read_sql(query, engine)

result

         Order ID  Customer Name     Sales    Profit
0  US-2023-103800  Darren Powers    16.448    5.5512
1  US-2023-112326  Phillina Ober     3.540   -5.4870
2  US-2023-112326  Phillina Ober    11.784    4.2717
3  US-2023-112326  Phillina Ober   272.736  -64.7748
4  US-2023-141817     Mick Brown    19.536    4.8840
5  US-2023-167199  Maria Etezadi  2573.820  746.4078
6  US-2023-167199  Maria Etezadi     5.480    1.4796
7  US-2023-106054  Jack O'Briant    12.780    5.2398
8  US-2023-167199  Maria Etezadi   609.980  274.4910
9  US-2023-167199  Maria Etezadi    31.120    0.3112

In [54]:
query = """
SELECT "Order ID", "Customer Name", "Sales", "Profit"
FROM sales
WHERE "Sales" > 1000
LIMIT 10;
"""

result = pd.read_sql(query, engine)

result

         Order ID       Customer Name     Sales    Profit
0  US-2023-167199       Maria Etezadi  2573.820  746.4078
1  US-2023-157147        Brian Dahlen  1325.850  238.6530
2  US-2023-147627        Hunter Lopez  1067.940  224.2674
3  US-2023-127614    Natalie Fritzler  1256.220   75.3732
4  US-2023-125521  Christine Kargatis  1139.920  284.9800
5  US-2023-148838      Christine Phan  1071.576 -553.6476
6  US-2023-148838      Christine Phan  1579.746 -447.5947
7  US-2023-111871       Eileen Kiefer  1198.330   70.4900
8  US-2023-131275    Sample Company A  1856.190  334.1142
9  US-2023-131275    Sample Company A  1279.968  415.9896

In [55]:
query = """
SELECT "Order ID", "Customer Name", "Sales", "Profit"
FROM sales
ORDER BY "Sales" DESC
LIMIT 10;
"""

result = pd.read_sql(query, engine)

result

         Order ID       Customer Name      Sales     Profit
0  US-2023-145317         Sean Miller  22638.480 -1811.0784
1  US-2025-118689        Tamara Chand  17499.950  8399.9760
2  US-2026-140151        Raymond Buch  13999.960  6719.9808
3  US-2026-127180        Tom Ashbrook  11199.968  3919.9888
4  US-2026-166709        Hunter Lopez  10499.970  5039.9856
5  US-2025-117121       Adrian Barton   9892.740  4946.3700
6  US-2023-116904        Sanjit Chand   9449.950  4630.4755
7  US-2025-107440        Bill Shonely   9099.930  2365.9818
8  US-2025-158841        Sanjit Engle   8749.950  2799.9840
9  US-2025-143714  Christopher Conant   8399.976  1119.9968

In [56]:
query = """
SELECT
    "Category",
    SUM("Sales") AS total_sales
FROM sales
GROUP BY "Category"
ORDER BY total_sales DESC;
"""

result = pd.read_sql(query, engine)

result

          Category  total_sales
0       Technology  839893.2790
1        Furniture  754747.7613
2  Office Supplies  731893.3140

In [57]:
query = """
SELECT
    "Category",
    SUM("Sales") AS total_sales
FROM sales
GROUP BY "Category"
HAVING SUM("Sales") > 500000
ORDER BY total_sales DESC;
"""

result = pd.read_sql(query, engine)

result

          Category  total_sales
0       Technology  839893.2790
1        Furniture  754747.7613
2  Office Supplies  731893.3140

In [58]:
query = """
CREATE TABLE IF NOT EXISTS customers AS
SELECT DISTINCT
    "Customer ID",
    "Customer Name",
    "Segment"
FROM sales;
"""

with engine.begin() as connection:
    connection.exec_driver_sql(query)

print("Customers table created!")

Customers table created!

In [59]:
query = """
CREATE TABLE IF NOT EXISTS products AS
SELECT DISTINCT
    "Product ID",
    "Product Name",
    "Category",
    "Sub-Category"
FROM sales;
"""

with engine.begin() as connection:
    connection.exec_driver_sql(query)

print("Products table created!")

Products table created!

In [60]:
query = """
SELECT
    s."Order ID",
    s."Customer ID",
    c."Customer Name",
    c."Segment",
    s."Sales",
    s."Profit"
FROM sales s
JOIN customers c
    ON s."Customer ID" = c."Customer ID"
LIMIT 10;
"""

result = pd.read_sql(query, engine)

result

         Order ID Customer ID  Customer Name      Segment     Sales    Profit
0  US-2023-103800    DP-13000  Darren Powers     Consumer    16.448    5.5512
1  US-2023-112326    PO-19195  Phillina Ober  Home Office     3.540   -5.4870
2  US-2023-112326    PO-19195  Phillina Ober  Home Office    11.784    4.2717
3  US-2023-112326    PO-19195  Phillina Ober  Home Office   272.736  -64.7748
4  US-2023-141817    MB-18085     Mick Brown     Consumer    19.536    4.8840
5  US-2023-167199    ME-17320  Maria Etezadi  Home Office  2573.820  746.4078
6  US-2023-167199    ME-17320  Maria Etezadi  Home Office     5.480    1.4796
7  US-2023-106054    JO-15145  Jack O'Briant    Corporate    12.780    5.2398
8  US-2023-167199    ME-17320  Maria Etezadi  Home Office   609.980  274.4910
9  US-2023-167199    ME-17320  Maria Etezadi  Home Office    31.120    0.3112

In [61]:
query = """
SELECT
    s."Order ID",
    c."Customer Name",
    c."Segment",
    s."Sales",
    s."Profit"
FROM sales AS s
INNER JOIN customers AS c
    ON s."Customer ID" = c."Customer ID"
LIMIT 10;
"""

pd.read_sql(query, engine)

         Order ID  Customer Name      Segment     Sales    Profit
0  US-2023-103800  Darren Powers     Consumer    16.448    5.5512
1  US-2023-112326  Phillina Ober  Home Office     3.540   -5.4870
2  US-2023-112326  Phillina Ober  Home Office    11.784    4.2717
3  US-2023-112326  Phillina Ober  Home Office   272.736  -64.7748
4  US-2023-141817     Mick Brown     Consumer    19.536    4.8840
5  US-2023-167199  Maria Etezadi  Home Office  2573.820  746.4078
6  US-2023-167199  Maria Etezadi  Home Office     5.480    1.4796
7  US-2023-106054  Jack O'Briant    Corporate    12.780    5.2398
8  US-2023-167199  Maria Etezadi  Home Office   609.980  274.4910
9  US-2023-167199  Maria Etezadi  Home Office    31.120    0.3112

In [62]:
query = """
SELECT
    s."Order ID",
    s."Customer ID",
    c."Customer Name",
    s."Sales"
FROM sales AS s
LEFT JOIN customers AS c
    ON s."Customer ID" = c."Customer ID"
LIMIT 10;
"""

pd.read_sql(query, engine)

         Order ID Customer ID  Customer Name     Sales
0  US-2023-103800    DP-13000  Darren Powers    16.448
1  US-2023-112326    PO-19195  Phillina Ober     3.540
2  US-2023-112326    PO-19195  Phillina Ober    11.784
3  US-2023-112326    PO-19195  Phillina Ober   272.736
4  US-2023-141817    MB-18085     Mick Brown    19.536
5  US-2023-167199    ME-17320  Maria Etezadi  2573.820
6  US-2023-167199    ME-17320  Maria Etezadi     5.480
7  US-2023-106054    JO-15145  Jack O'Briant    12.780
8  US-2023-167199    ME-17320  Maria Etezadi   609.980
9  US-2023-167199    ME-17320  Maria Etezadi    31.120

In [63]:
query = """
SELECT
    s."Order ID",
    c."Customer Name",
    p."Product Name",
    p."Category",
    s."Sales",
    s."Profit"
FROM sales AS s
JOIN customers AS c
    ON s."Customer ID" = c."Customer ID"
JOIN products AS p
    ON s."Product ID" = p."Product ID"
LIMIT 10;
"""

pd.read_sql(query, engine)

,Order ID,Customer Name,Product Name,Category,Sales,Profit
0,US-2023-103800,Darren Powers,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",Office Supplies,16.448,5.5512
1,US-2023-112326,Phillina Ober,GBC Standard Plastic Binding Systems Combs,Office Supplies,3.540,-5.4870
2,US-2023-112326,Phillina Ober,Avery 508,Office Supplies,11.784,4.2717
3,US-2023-112326,Phillina Ober,SAFCO Boltless Steel Shelving,Office Supplies,272.736,-64.7748
4,US-2023-141817,Mick Brown,Avery Hi-Liter EverBold Pen Style Fluorescent ...,Office Supplies,19.536,4.8840
5,US-2023-167199,Maria Etezadi,Global Deluxe High-Back Manager's Chair,Furniture,2573.820,746.4078
6,US-2023-167199,Maria Etezadi,Rogers Handheld Barrel Pencil Sharpener,Office Supplies,5.480,1.4796
7,US-2023-106054,Jack O'Briant,"Dixon Prang Watercolor Pencils, 10-Color Set w...",Office Supplies,12.780,5.2398
8,US-2023-167199,Maria Etezadi,GBC Binding covers,Office Supplies,609.980,274.4910
9,US-2023-167199,Maria Etezadi,Ibico Hi-Tech Manual Binding System,Office Supplies,609.980,274.4910

In [64]:
query = """
SELECT
    "Order ID",
    "Customer Name",
    "Sales"
FROM sales
WHERE "Sales" > (
    SELECT AVG("Sales")
    FROM sales
)
ORDER BY "Sales" DESC
LIMIT 10;
"""

pd.read_sql(query, engine)

         Order ID       Customer Name      Sales
0  US-2023-145317         Sean Miller  22638.480
1  US-2025-118689        Tamara Chand  17499.950
2  US-2026-140151        Raymond Buch  13999.960
3  US-2026-127180        Tom Ashbrook  11199.968
4  US-2026-166709        Hunter Lopez  10499.970
5  US-2025-117121       Adrian Barton   9892.740
6  US-2023-116904        Sanjit Chand   9449.950
7  US-2025-107440        Bill Shonely   9099.930
8  US-2025-158841        Sanjit Engle   8749.950
9  US-2025-143714  Christopher Conant   8399.976

In [65]:
query = """
SELECT
    "Customer Name",
    SUM("Sales") AS total_sales
FROM sales
GROUP BY "Customer Name"
HAVING SUM("Sales") > (
    SELECT AVG(customer_total)
    FROM (
        SELECT SUM("Sales") AS customer_total
        FROM sales
        GROUP BY "Customer Name"
    )
)
ORDER BY total_sales DESC;
"""

pd.read_sql(query, engine)

     Customer Name  total_sales
0      Sean Miller    25043.050
1     Tamara Chand    19052.218
2     Raymond Buch    15117.339
3     Tom Ashbrook    14595.620
4    Adrian Barton    14473.571
..             ...          ...
293  Becky Castell     2933.676
294     Julie Kriz     2932.484
295    Shaun Weien     2921.544
296   Maris LaWare     2921.500
297       Rob Dowd     2912.894

[298 rows x 2 columns]

In [66]:
query = """
WITH customer_sales AS (
    SELECT
        "Customer ID",
        "Customer Name",
        SUM("Sales") AS total_sales
    FROM sales
    GROUP BY
        "Customer ID",
        "Customer Name"
)
SELECT *
FROM customer_sales
ORDER BY total_sales DESC
LIMIT 10;
"""

pd.read_sql(query, engine)

  Customer ID       Customer Name  total_sales
0    SM-20320         Sean Miller    25043.050
1    TC-20980        Tamara Chand    19052.218
2    RB-19360        Raymond Buch    15117.339
3    TA-21385        Tom Ashbrook    14595.620
4    AB-10105       Adrian Barton    14473.571
5    KL-16645        Ken Lonsdale    14175.229
6    SC-20095        Sanjit Chand    14142.334
7    HL-15040        Hunter Lopez    12873.298
8    SE-20110        Sanjit Engle    12209.438
9    CC-12370  Christopher Conant    12129.072

In [67]:
query = """
WITH customer_sales AS (
    SELECT
        "Customer ID",
        "Customer Name",
        SUM("Sales") AS total_sales
    FROM sales
    GROUP BY
        "Customer ID",
        "Customer Name"
),

customer_profit AS (
    SELECT
        "Customer ID",
        SUM("Profit") AS total_profit
    FROM sales
    GROUP BY "Customer ID"
)

SELECT
    cs."Customer Name",
    cs.total_sales,
    cp.total_profit
FROM customer_sales cs
JOIN customer_profit cp
    ON cs."Customer ID" = cp."Customer ID"
ORDER BY cs.total_sales DESC
LIMIT 10;
"""

pd.read_sql(query, engine)

        Customer Name  total_sales  total_profit
0         Sean Miller    25043.050    -1980.7393
1        Tamara Chand    19052.218     8981.3239
2        Raymond Buch    15117.339     6976.0959
3        Tom Ashbrook    14595.620     4703.7883
4       Adrian Barton    14473.571     5444.8055
5        Ken Lonsdale    14175.229      806.8550
6        Sanjit Chand    14142.334     5757.4119
7        Hunter Lopez    12873.298     5622.4292
8        Sanjit Engle    12209.438     2650.6769
9  Christopher Conant    12129.072     2177.0493

In [68]:
query = """
SELECT
    "Customer Name",
    "Sales",
    ROW_NUMBER() OVER (
        ORDER BY "Sales" DESC
    ) AS row_num
FROM sales
LIMIT 10;
"""

pd.read_sql(query, engine)

        Customer Name      Sales  row_num
0         Sean Miller  22638.480        1
1        Tamara Chand  17499.950        2
2        Raymond Buch  13999.960        3
3        Tom Ashbrook  11199.968        4
4        Hunter Lopez  10499.970        5
5       Adrian Barton   9892.740        6
6        Sanjit Chand   9449.950        7
7        Bill Shonely   9099.930        8
8        Sanjit Engle   8749.950        9
9  Christopher Conant   8399.976       10

In [69]:
query = """
SELECT
    "Customer Name",
    "Sales",
    RANK() OVER (
        ORDER BY "Sales" DESC
    ) AS sales_rank
FROM sales
LIMIT 20;
"""

pd.read_sql(query, engine)

           Customer Name      Sales  sales_rank
0            Sean Miller  22638.480           1
1           Tamara Chand  17499.950           2
2           Raymond Buch  13999.960           3
3           Tom Ashbrook  11199.968           4
4           Hunter Lopez  10499.970           5
5          Adrian Barton   9892.740           6
6           Sanjit Chand   9449.950           7
7           Bill Shonely   9099.930           8
8           Sanjit Engle   8749.950           9
9     Christopher Conant   8399.976          10
10          Ken Lonsdale   8187.650          11
11          Becky Martin   8159.952          12
12        Grant Thornton   7999.980          13
13      Tom Boeckenhauer   6999.960          14
14  Christopher Martinez   6354.950          15
15           Andy Reiter   5443.960          16
16         Daniel Raglin   5399.910          17
17          Todd Sumrall   5199.960          18
18          Greg Guthrie   5199.960          18
19             Jane Waco   5083.960          20

In [70]:
query = """
SELECT
    "Customer Name",
    "Sales",
    DENSE_RANK() OVER (
        ORDER BY "Sales" DESC
    ) AS sales_rank
FROM sales
LIMIT 20;
"""

pd.read_sql(query, engine)

           Customer Name      Sales  sales_rank
0            Sean Miller  22638.480           1
1           Tamara Chand  17499.950           2
2           Raymond Buch  13999.960           3
3           Tom Ashbrook  11199.968           4
4           Hunter Lopez  10499.970           5
5          Adrian Barton   9892.740           6
6           Sanjit Chand   9449.950           7
7           Bill Shonely   9099.930           8
8           Sanjit Engle   8749.950           9
9     Christopher Conant   8399.976          10
10          Ken Lonsdale   8187.650          11
11          Becky Martin   8159.952          12
12        Grant Thornton   7999.980          13
13      Tom Boeckenhauer   6999.960          14
14  Christopher Martinez   6354.950          15
15           Andy Reiter   5443.960          16
16         Daniel Raglin   5399.910          17
17          Todd Sumrall   5199.960          18
18          Greg Guthrie   5199.960          18
19             Jane Waco   5083.960          19

In [71]:
query = """
WITH customer_sales AS (
    SELECT
        "Customer ID",
        "Customer Name",
        SUM("Sales") AS total_sales
    FROM sales
    GROUP BY
        "Customer ID",
        "Customer Name"
)

SELECT
    "Customer Name",
    total_sales,
    RANK() OVER (
        ORDER BY total_sales DESC
    ) AS customer_rank
FROM customer_sales
ORDER BY customer_rank
LIMIT 10;
"""

pd.read_sql(query, engine)

        Customer Name  total_sales  customer_rank
0         Sean Miller    25043.050              1
1        Tamara Chand    19052.218              2
2        Raymond Buch    15117.339              3
3        Tom Ashbrook    14595.620              4
4       Adrian Barton    14473.571              5
5        Ken Lonsdale    14175.229              6
6        Sanjit Chand    14142.334              7
7        Hunter Lopez    12873.298              8
8        Sanjit Engle    12209.438              9
9  Christopher Conant    12129.072             10

In [72]:
query = """
WITH customer_sales AS (
    SELECT
        "Customer ID",
        "Customer Name",
        "Segment",
        SUM("Sales") AS total_sales
    FROM sales
    GROUP BY
        "Customer ID",
        "Customer Name",
        "Segment"
)

SELECT
    "Customer Name",
    "Segment",
    total_sales,
    RANK() OVER (
        PARTITION BY "Segment"
        ORDER BY total_sales DESC
    ) AS segment_rank
FROM customer_sales
ORDER BY "Segment", segment_rank;
"""

pd.read_sql(query, engine)

         Customer Name      Segment  total_sales  segment_rank
0         Raymond Buch     Consumer    15117.339             1
1        Adrian Barton     Consumer    14473.571             2
2         Ken Lonsdale     Consumer    14175.229             3
3         Sanjit Chand     Consumer    14142.334             4
4         Hunter Lopez     Consumer    12873.298             5
..                 ...          ...          ...           ...
799  Anthony Garverick  Home Office      170.584           145
800      Dianna Arnett  Home Office      156.760           146
801          Ed Ludwig  Home Office      124.280           147
802       Adrian Shami  Home Office       58.820           148
803         Roy Skaria  Home Office       22.328           149

[804 rows x 4 columns]

In [73]:
query = """
WITH monthly_sales AS (
    SELECT
        strftime('%Y-%m', "Order Date") AS month,
        SUM("Sales") AS total_sales
    FROM sales
    GROUP BY month
)

SELECT
    month,
    total_sales,
    LAG(total_sales) OVER (
        ORDER BY month
    ) AS previous_month_sales
FROM monthly_sales
ORDER BY month;
"""

pd.read_sql(query, engine)

      month  total_sales  previous_month_sales
0   2023-01   14518.0550                   NaN
1   2023-02    4519.8920            14518.0550
2   2023-03   56933.9090             4519.8920
3   2023-04   28295.3450            56933.9090
4   2023-05   26319.7670            28295.3450
5   2023-06   34669.4796            26319.7670
6   2023-07   33946.3930            34669.4796
7   2023-08   28918.3385            33946.3930
8   2023-09   82670.4288            28918.3385
9   2023-10   32413.3390            82670.4288
10  2023-11   78826.9567            32413.3390
11  2023-12   72008.3085            78826.9567
12  2024-01   18461.9156            72008.3085
13  2024-02   11951.4110            18461.9156
14  2024-03   39978.6280            11951.4110
15  2024-04   34195.2085            39978.6280
16  2024-05   30246.9465            34195.2085
17  2024-06   24797.2920            30246.9465
18  2024-07   28765.3250            24797.2920
19  2024-08   37057.0042            28765.3250
20  2024-09   64627.0460            37057.0042
21  2024-10   31407.1335            64627.0460
22  2024-11   75972.5635            31407.1335
23  2024-12   75532.5572            75972.5635
24  2025-01   18830.3310            75532.5572
25  2025-02   22978.8150            18830.3310
26  2025-03   53031.0690            22978.8150
27  2025-04   38829.1590            53031.0690
28  2025-05   57042.8380            38829.1590
29  2025-06   40937.1480            57042.8380
30  2025-07   40300.4990            40937.1480
31  2025-08   31716.8143            40300.4990
32  2025-09   73521.6629            31716.8143
33  2025-10   59831.0010            73521.6629
34  2025-11   79411.9658            59831.0010
35  2025-12   97502.2770            79411.9658
36  2026-01   44259.2140            97502.2770
37  2026-02   20301.1334            44259.2140
38  2026-03   60728.4808            20301.1334
39  2026-04   36779.0361            60728.4808
40  2026-05   45155.4822            36779.0361
41  2026-06   53056.0777            45155.4822
42  2026-07   45989.4960            53056.0777
43  2026-08   64129.7580            45989.4960
44  2026-09   88064.5320            64129.7580
45  2026-10   83474.7832            88064.5320
46  2026-11  118454.5050            83474.7832
47  2026-12   85175.0328           118454.5050

In [74]:
query = """
WITH monthly_sales AS (
    SELECT
        strftime('%Y-%m', "Order Date") AS month,
        SUM("Sales") AS total_sales
    FROM sales
    GROUP BY month
),

comparison AS (
    SELECT
        month,
        total_sales,
        LAG(total_sales) OVER (
            ORDER BY month
        ) AS previous_month_sales
    FROM monthly_sales
)

SELECT
    month,
    total_sales,
    previous_month_sales,
    total_sales - previous_month_sales AS sales_difference
FROM comparison
ORDER BY month;
"""

pd.read_sql(query, engine)

      month  total_sales  previous_month_sales  sales_difference
0   2023-01   14518.0550                   NaN               NaN
1   2023-02    4519.8920            14518.0550        -9998.1630
2   2023-03   56933.9090             4519.8920        52414.0170
3   2023-04   28295.3450            56933.9090       -28638.5640
4   2023-05   26319.7670            28295.3450        -1975.5780
5   2023-06   34669.4796            26319.7670         8349.7126
6   2023-07   33946.3930            34669.4796         -723.0866
7   2023-08   28918.3385            33946.3930        -5028.0545
8   2023-09   82670.4288            28918.3385        53752.0903
9   2023-10   32413.3390            82670.4288       -50257.0898
10  2023-11   78826.9567            32413.3390        46413.6177
11  2023-12   72008.3085            78826.9567        -6818.6482
12  2024-01   18461.9156            72008.3085       -53546.3929
13  2024-02   11951.4110            18461.9156        -6510.5046
14  2024-03   39978.6280            11951.4110        28027.2170
15  2024-04   34195.2085            39978.6280        -5783.4195
16  2024-05   30246.9465            34195.2085        -3948.2620
17  2024-06   24797.2920            30246.9465        -5449.6545
18  2024-07   28765.3250            24797.2920         3968.0330
19  2024-08   37057.0042            28765.3250         8291.6792
20  2024-09   64627.0460            37057.0042        27570.0418
21  2024-10   31407.1335            64627.0460       -33219.9125
22  2024-11   75972.5635            31407.1335        44565.4300
23  2024-12   75532.5572            75972.5635         -440.0063
24  2025-01   18830.3310            75532.5572       -56702.2262
25  2025-02   22978.8150            18830.3310         4148.4840
26  2025-03   53031.0690            22978.8150        30052.2540
27  2025-04   38829.1590            53031.0690       -14201.9100
28  2025-05   57042.8380            38829.1590        18213.6790
29  2025-06   40937.1480            57042.8380       -16105.6900
30  2025-07   40300.4990            40937.1480         -636.6490
31  2025-08   31716.8143            40300.4990        -8583.6847
32  2025-09   73521.6629            31716.8143        41804.8486
33  2025-10   59831.0010            73521.6629       -13690.6619
34  2025-11   79411.9658            59831.0010        19580.9648
35  2025-12   97502.2770            79411.9658        18090.3112
36  2026-01   44259.2140            97502.2770       -53243.0630
37  2026-02   20301.1334            44259.2140       -23958.0806
38  2026-03   60728.4808            20301.1334        40427.3474
39  2026-04   36779.0361            60728.4808       -23949.4447
40  2026-05   45155.4822            36779.0361         8376.4461
41  2026-06   53056.0777            45155.4822         7900.5955
42  2026-07   45989.4960            53056.0777        -7066.5817
43  2026-08   64129.7580            45989.4960        18140.2620
44  2026-09   88064.5320            64129.7580        23934.7740
45  2026-10   83474.7832            88064.5320        -4589.7488
46  2026-11  118454.5050            83474.7832        34979.7218
47  2026-12   85175.0328           118454.5050       -33279.4722

In [75]:
query = """
SELECT
    "Order ID",
    "Sales",
    "Profit",
    CASE
        WHEN "Profit" > 0 THEN 'Profitable'
        WHEN "Profit" < 0 THEN 'Loss'
        ELSE 'Break Even'
    END AS profit_status
FROM sales
LIMIT 20;
"""

pd.read_sql(query, engine)

          Order ID     Sales    Profit profit_status
0   US-2023-103800    16.448    5.5512    Profitable
1   US-2023-112326     3.540   -5.4870          Loss
2   US-2023-112326    11.784    4.2717    Profitable
3   US-2023-112326   272.736  -64.7748          Loss
4   US-2023-141817    19.536    4.8840    Profitable
5   US-2023-167199  2573.820  746.4078    Profitable
6   US-2023-167199     5.480    1.4796    Profitable
7   US-2023-106054    12.780    5.2398    Profitable
8   US-2023-167199   609.980  274.4910    Profitable
9   US-2023-167199    31.120    0.3112    Profitable
10  US-2023-167199     6.540    3.0084    Profitable
11  US-2023-130813    19.440    9.3312    Profitable
12  US-2023-167199   755.960  204.1092    Profitable
13  US-2023-167199   391.980  113.6742    Profitable
14  US-2023-105417    76.728  -53.7096          Loss
15  US-2023-105417    10.430  -18.2525          Loss
16  US-2023-135405     9.344    1.1680    Profitable
17  US-2023-135405    31.200    9.7500    Profitable
18  US-2023-149020    51.940   21.2954    Profitable
19  US-2023-149020     2.890    1.3583    Profitable

In [76]:
query = """
SELECT
    "Order ID",
    "Sales",
    "Profit",
    CASE
        WHEN "Profit" > 0 THEN 'Profitable'
        WHEN "Profit" < 0 THEN 'Loss'
        ELSE 'Break Even'
    END AS profit_status
FROM sales
LIMIT 20;
"""

pd.read_sql(query, engine)

          Order ID     Sales    Profit profit_status
0   US-2023-103800    16.448    5.5512    Profitable
1   US-2023-112326     3.540   -5.4870          Loss
2   US-2023-112326    11.784    4.2717    Profitable
3   US-2023-112326   272.736  -64.7748          Loss
4   US-2023-141817    19.536    4.8840    Profitable
5   US-2023-167199  2573.820  746.4078    Profitable
6   US-2023-167199     5.480    1.4796    Profitable
7   US-2023-106054    12.780    5.2398    Profitable
8   US-2023-167199   609.980  274.4910    Profitable
9   US-2023-167199    31.120    0.3112    Profitable
10  US-2023-167199     6.540    3.0084    Profitable
11  US-2023-130813    19.440    9.3312    Profitable
12  US-2023-167199   755.960  204.1092    Profitable
13  US-2023-167199   391.980  113.6742    Profitable
14  US-2023-105417    76.728  -53.7096          Loss
15  US-2023-105417    10.430  -18.2525          Loss
16  US-2023-135405     9.344    1.1680    Profitable
17  US-2023-135405    31.200    9.7500    Profitable
18  US-2023-149020    51.940   21.2954    Profitable
19  US-2023-149020     2.890    1.3583    Profitable

In [77]:
query = """
CREATE VIEW IF NOT EXISTS customer_sales_summary AS
SELECT
    "Customer ID",
    "Customer Name",
    "Segment",
    SUM("Sales") AS total_sales,
    SUM("Profit") AS total_profit
FROM sales
GROUP BY
    "Customer ID",
    "Customer Name",
    "Segment";
"""

with engine.begin() as connection:
    connection.exec_driver_sql(query)

print("View created")

View created

In [78]:
query = """
SELECT *
FROM customer_sales_summary
ORDER BY total_sales DESC
LIMIT 10;
"""

pd.read_sql(query, engine)

  Customer ID       Customer Name      Segment  total_sales  total_profit
0    SM-20320         Sean Miller  Home Office    25043.050    -1980.7393
1    TC-20980        Tamara Chand    Corporate    19052.218     8981.3239
2    RB-19360        Raymond Buch     Consumer    15117.339     6976.0959
3    TA-21385        Tom Ashbrook  Home Office    14595.620     4703.7883
4    AB-10105       Adrian Barton     Consumer    14473.571     5444.8055
5    KL-16645        Ken Lonsdale     Consumer    14175.229      806.8550
6    SC-20095        Sanjit Chand     Consumer    14142.334     5757.4119
7    HL-15040        Hunter Lopez     Consumer    12873.298     5622.4292
8    SE-20110        Sanjit Engle     Consumer    12209.438     2650.6769
9    CC-12370  Christopher Conant     Consumer    12129.072     2177.0493

1️⃣ Which 10 customers generate the highest sales?

In [79]:
query = """
WITH customer_sales AS (
    SELECT
        "Customer ID",
        "Customer Name",
        SUM("Sales") AS total_sales
    FROM sales
    GROUP BY
        "Customer ID",
        "Customer Name"
)

SELECT
    "Customer Name",
    total_sales,
    RANK() OVER (
        ORDER BY total_sales DESC
    ) AS customer_rank
FROM customer_sales
ORDER BY customer_rank
LIMIT 10;
"""

result = pd.read_sql(query, engine)
result

        Customer Name  total_sales  customer_rank
0         Sean Miller    25043.050              1
1        Tamara Chand    19052.218              2
2        Raymond Buch    15117.339              3
3        Tom Ashbrook    14595.620              4
4       Adrian Barton    14473.571              5
5        Ken Lonsdale    14175.229              6
6        Sanjit Chand    14142.334              7
7        Hunter Lopez    12873.298              8
8        Sanjit Engle    12209.438              9
9  Christopher Conant    12129.072             10

2️⃣ Which products generate the highest revenue?

In [80]:
query = """
SELECT
    "Product ID",
    "Product Name",
    SUM("Sales") AS total_sales
FROM sales
GROUP BY
    "Product ID",
    "Product Name"
ORDER BY total_sales DESC
LIMIT 10;
"""

result = pd.read_sql(query, engine)
result

,Product ID,Product Name,total_sales
0,TEC-CO-10004722,Canon imageCLASS 2200 Advanced Copier,61599.824
1,OFF-BI-10003527,Fellowes PB500 Electric Punch Plastic Comb Bin...,27453.384
2,TEC-MA-10002412,Cisco TelePresence System EX90 Videoconferenci...,22638.480
3,FUR-CH-10002024,HON 5400 Series Task Chairs for Big and Tall,21870.576
4,OFF-BI-10001359,GBC DocuBind TL300 Electric Binding System,19823.479
5,OFF-BI-10000545,GBC Ibimaster 500 Manual ProClick Binding System,19024.500
6,TEC-CO-10001449,Hewlett Packard LaserJet 3310 Copier,18839.686
7,TEC-MA-10001127,HP Designjet T520 Inkjet Large Format Printer ...,18374.895
8,OFF-BI-10004995,GBC DocuBind P400 Electric Binding System,17965.068
9,OFF-SU-10000151,High Speed Automatic Electric Letter Opener,17030.312

3️⃣ Which products generate the highest profit?

In [81]:
query = """
SELECT
    "Product ID",
    "Product Name",
    SUM("Profit") AS total_profit
FROM sales
GROUP BY
    "Product ID",
    "Product Name"
ORDER BY total_profit DESC
LIMIT 10;
"""

result = pd.read_sql(query, engine)
result

,Product ID,Product Name,total_profit
0,TEC-CO-10004722,Canon imageCLASS 2200 Advanced Copier,25199.9280
1,OFF-BI-10003527,Fellowes PB500 Electric Punch Plastic Comb Bin...,7753.0390
2,TEC-CO-10001449,Hewlett Packard LaserJet 3310 Copier,6983.8836
3,TEC-CO-10003763,Canon PC1060 Personal Laser Copier,4570.9347
4,TEC-MA-10001127,HP Designjet T520 Inkjet Large Format Printer ...,4094.9766
5,TEC-MA-10003979,Ativa V4110MDD Micro-Cut Shredder,3772.9461
6,TEC-MA-10001047,"3D Systems Cube Printer, 2nd Generation, Magenta",3717.9714
7,TEC-AC-10002049,Plantronics Savi W720 Multi-Device Wireless He...,3696.2820
8,OFF-BI-10001120,Ibico EPK-21 Electric Binding System,3345.2823
9,TEC-MA-10000045,Zebra ZM400 Thermal Label Printer,3343.5360

4️⃣ Which products are causing losses?

In [82]:
query = """
SELECT
    "Product ID",
    "Product Name",
    SUM("Profit") AS total_profit
FROM sales
GROUP BY
    "Product ID",
    "Product Name"
HAVING SUM("Profit") < 0
ORDER BY total_profit ASC
LIMIT 10;
"""

result = pd.read_sql(query, engine)
result

,Product ID,Product Name,total_profit
0,TEC-MA-10000418,Cubify CubeX 3D Printer Double Head Print,-8879.9704
1,TEC-MA-10000822,Lexmark MX611dhe Monochrome Laser Printer,-4589.9730
2,TEC-MA-10004125,Cubify CubeX 3D Printer Triple Head Print,-3839.9904
3,FUR-TA-10000198,Chromcraft Bull-Nose Wood Oval Conference Tabl...,-2876.1156
4,FUR-TA-10001889,Bush Advantage Collection Racetrack Conference...,-1934.3976
5,OFF-BI-10004995,GBC DocuBind P400 Electric Binding System,-1878.1662
6,TEC-MA-10002412,Cisco TelePresence System EX90 Videoconferenci...,-1811.0784
7,OFF-SU-10002881,Martin Yale Chadless Opener Electric Letter Op...,-1299.1836
8,FUR-TA-10001950,Balt Solid Wood Round Tables,-1201.0581
9,FUR-TA-10004289,BoxOffice By Design Rectangular and Half-Moon ...,-1148.4375

5️⃣ Which region generates the most sales?

In [83]:
query = """
SELECT
    "Region",
    SUM("Sales") AS total_sales,
    SUM("Profit") AS total_profit
FROM sales
GROUP BY "Region"
ORDER BY total_sales DESC;
"""

result = pd.read_sql(query, engine)
result

    Region  total_sales  total_profit
0     West  739813.6085   110798.8170
1     East  691828.1680    94883.2603
2  Central  503170.6728    39865.3070
3    South  391721.9050    46749.4303

6️⃣ Which category performs best?

In [84]:
query = """
SELECT
    "Category",
    SUM("Sales") AS total_sales,
    SUM("Profit") AS total_profit,
    AVG("Profit") AS average_profit
FROM sales
GROUP BY "Category"
ORDER BY total_profit DESC;
"""

result = pd.read_sql(query, engine)
result

          Category  total_sales  total_profit  average_profit
0       Technology  839893.2790   146543.3756       78.575537
1  Office Supplies  731893.3140   126023.4434       20.565183
2        Furniture  754747.7613    19729.9956        8.964105

7️⃣ Which customer segment is most profitable?

In [85]:
query = """
SELECT
    "Segment",
    COUNT(DISTINCT "Customer ID") AS customers,
    SUM("Sales") AS total_sales,
    SUM("Profit") AS total_profit
FROM sales
GROUP BY "Segment"
ORDER BY total_profit DESC;
"""

result = pd.read_sql(query, engine)
result

       Segment  customers   total_sales  total_profit
0     Consumer        416  1.170660e+06   136371.4463
1    Corporate        239  7.158061e+05    94249.6400
2  Home Office        149  4.400684e+05    61675.7283

8️⃣ What is the monthly sales trend?

In [86]:
query = """
WITH monthly_sales AS (
    SELECT
        strftime('%Y-%m', "Order Date") AS month,
        SUM("Sales") AS total_sales
    FROM sales
    GROUP BY month
)

SELECT
    month,
    total_sales,
    LAG(total_sales) OVER (
        ORDER BY month
    ) AS previous_month_sales
FROM monthly_sales
ORDER BY month;
"""

result = pd.read_sql(query, engine)
result

      month  total_sales  previous_month_sales
0   2023-01   14518.0550                   NaN
1   2023-02    4519.8920            14518.0550
2   2023-03   56933.9090             4519.8920
3   2023-04   28295.3450            56933.9090
4   2023-05   26319.7670            28295.3450
5   2023-06   34669.4796            26319.7670
6   2023-07   33946.3930            34669.4796
7   2023-08   28918.3385            33946.3930
8   2023-09   82670.4288            28918.3385
9   2023-10   32413.3390            82670.4288
10  2023-11   78826.9567            32413.3390
11  2023-12   72008.3085            78826.9567
12  2024-01   18461.9156            72008.3085
13  2024-02   11951.4110            18461.9156
14  2024-03   39978.6280            11951.4110
15  2024-04   34195.2085            39978.6280
16  2024-05   30246.9465            34195.2085
17  2024-06   24797.2920            30246.9465
18  2024-07   28765.3250            24797.2920
19  2024-08   37057.0042            28765.3250
20  2024-09   64627.0460            37057.0042
21  2024-10   31407.1335            64627.0460
22  2024-11   75972.5635            31407.1335
23  2024-12   75532.5572            75972.5635
24  2025-01   18830.3310            75532.5572
25  2025-02   22978.8150            18830.3310
26  2025-03   53031.0690            22978.8150
27  2025-04   38829.1590            53031.0690
28  2025-05   57042.8380            38829.1590
29  2025-06   40937.1480            57042.8380
30  2025-07   40300.4990            40937.1480
31  2025-08   31716.8143            40300.4990
32  2025-09   73521.6629            31716.8143
33  2025-10   59831.0010            73521.6629
34  2025-11   79411.9658            59831.0010
35  2025-12   97502.2770            79411.9658
36  2026-01   44259.2140            97502.2770
37  2026-02   20301.1334            44259.2140
38  2026-03   60728.4808            20301.1334
39  2026-04   36779.0361            60728.4808
40  2026-05   45155.4822            36779.0361
41  2026-06   53056.0777            45155.4822
42  2026-07   45989.4960            53056.0777
43  2026-08   64129.7580            45989.4960
44  2026-09   88064.5320            64129.7580
45  2026-10   83474.7832            88064.5320
46  2026-11  118454.5050            83474.7832
47  2026-12   85175.0328           118454.5050

In [87]:
query = """
WITH monthly_sales AS (
    SELECT
        strftime('%Y-%m', "Order Date") AS month,
        SUM("Sales") AS total_sales
    FROM sales
    GROUP BY month
),

comparison AS (
    SELECT
        month,
        total_sales,
        LAG(total_sales) OVER (
            ORDER BY month
        ) AS previous_month_sales
    FROM monthly_sales
)

SELECT
    month,
    total_sales,
    previous_month_sales,
    total_sales - previous_month_sales AS sales_change
FROM comparison
ORDER BY month;
"""

result = pd.read_sql(query, engine)
result

      month  total_sales  previous_month_sales  sales_change
0   2023-01   14518.0550                   NaN           NaN
1   2023-02    4519.8920            14518.0550    -9998.1630
2   2023-03   56933.9090             4519.8920    52414.0170
3   2023-04   28295.3450            56933.9090   -28638.5640
4   2023-05   26319.7670            28295.3450    -1975.5780
5   2023-06   34669.4796            26319.7670     8349.7126
6   2023-07   33946.3930            34669.4796     -723.0866
7   2023-08   28918.3385            33946.3930    -5028.0545
8   2023-09   82670.4288            28918.3385    53752.0903
9   2023-10   32413.3390            82670.4288   -50257.0898
10  2023-11   78826.9567            32413.3390    46413.6177
11  2023-12   72008.3085            78826.9567    -6818.6482
12  2024-01   18461.9156            72008.3085   -53546.3929
13  2024-02   11951.4110            18461.9156    -6510.5046
14  2024-03   39978.6280            11951.4110    28027.2170
15  2024-04   34195.2085            39978.6280    -5783.4195
16  2024-05   30246.9465            34195.2085    -3948.2620
17  2024-06   24797.2920            30246.9465    -5449.6545
18  2024-07   28765.3250            24797.2920     3968.0330
19  2024-08   37057.0042            28765.3250     8291.6792
20  2024-09   64627.0460            37057.0042    27570.0418
21  2024-10   31407.1335            64627.0460   -33219.9125
22  2024-11   75972.5635            31407.1335    44565.4300
23  2024-12   75532.5572            75972.5635     -440.0063
24  2025-01   18830.3310            75532.5572   -56702.2262
25  2025-02   22978.8150            18830.3310     4148.4840
26  2025-03   53031.0690            22978.8150    30052.2540
27  2025-04   38829.1590            53031.0690   -14201.9100
28  2025-05   57042.8380            38829.1590    18213.6790
29  2025-06   40937.1480            57042.8380   -16105.6900
30  2025-07   40300.4990            40937.1480     -636.6490
31  2025-08   31716.8143            40300.4990    -8583.6847
32  2025-09   73521.6629            31716.8143    41804.8486
33  2025-10   59831.0010            73521.6629   -13690.6619
34  2025-11   79411.9658            59831.0010    19580.9648
35  2025-12   97502.2770            79411.9658    18090.3112
36  2026-01   44259.2140            97502.2770   -53243.0630
37  2026-02   20301.1334            44259.2140   -23958.0806
38  2026-03   60728.4808            20301.1334    40427.3474
39  2026-04   36779.0361            60728.4808   -23949.4447
40  2026-05   45155.4822            36779.0361     8376.4461
41  2026-06   53056.0777            45155.4822     7900.5955
42  2026-07   45989.4960            53056.0777    -7066.5817
43  2026-08   64129.7580            45989.4960    18140.2620
44  2026-09   88064.5320            64129.7580    23934.7740
45  2026-10   83474.7832            88064.5320    -4589.7488
46  2026-11  118454.5050            83474.7832    34979.7218
47  2026-12   85175.0328           118454.5050   -33279.4722

9️⃣ What is the average order value?

In [88]:
query = """
SELECT
    COUNT(DISTINCT "Order ID") AS total_orders,
    SUM("Sales") AS total_sales,
    SUM("Sales") / COUNT(DISTINCT "Order ID") AS average_order_value
FROM sales;
"""

result = pd.read_sql(query, engine)
result

   total_orders   total_sales  average_order_value
0          5111  2.326534e+06             455.2014

🔟 Which customers have high sales but low profit?

In [89]:
query = """
SELECT
    "Customer ID",
    "Customer Name",
    SUM("Sales") AS total_sales,
    SUM("Profit") AS total_profit
FROM sales
GROUP BY
    "Customer ID",
    "Customer Name"
HAVING
    SUM("Sales") > (
        SELECT AVG(customer_sales)
        FROM (
            SELECT SUM("Sales") AS customer_sales
            FROM sales
            GROUP BY "Customer ID"
        )
    )
    AND SUM("Profit") < 0
ORDER BY total_sales DESC;
"""

result = pd.read_sql(query, engine)
result

   Customer ID       Customer Name  total_sales  total_profit
0     SM-20320         Sean Miller   25043.0500    -1980.7393
1     BM-11140        Becky Martin   11789.6300    -1659.9581
2     GT-14635      Grant Thornton    9351.2120    -4108.6589
3     PF-19120        Peter Fuller    9062.8640     -614.2943
4     NF-18385    Natalie Fritzler    8322.8260    -1695.9714
5     SB-20290        Sean Braxton    8057.8910    -2082.7451
6     ZC-21910    Zuschuss Carroll    8025.7070    -1032.1490
7     JH-15985         Joseph Holt    7954.9980     -644.6982
8     JA-15970        Joseph Airdo    6491.0260     -819.4217
9     VW-21775     Victoria Wilson    6134.0380     -874.6645
10    CP-12340      Christine Phan    5888.2750    -1850.3029
11    CS-12505       Cindy Stewart    5690.0550    -6626.3895
12    RB-19795          Ross Baird    5633.3160     -461.7332
13    AA-10315          Alex Avila    5563.5600     -362.8825
14    SP-20620    Stefania Perrino    5440.3190     -270.4282
15    TP-21415        Tom Prescott    5329.0048    -1087.3898
16    KL-16555       Kelly Lampkin    5016.4880     -182.7813
17    LB-16795      Laurel Beltran    4985.6760      -52.1910
18    TB-21520     Tracy Blumstein    4737.4860    -1603.0451
19    SC-20770  Stewart Carmichael    4492.6570     -671.1874
20    TH-21550       Tracy Hopkins    4234.0960     -571.9678
21    MY-18295     Muhammed Yedwab    4152.6960     -371.7111
22    LF-17185         Luke Foster    3930.5090    -3583.9770
23    BS-11380        Bill Stewart    3887.8340      -17.5322
24    OT-18730         Olvera Toch    3818.6240     -925.1203
25    RO-19780        Rose O'Brian    3815.4780    -1262.5716
26    MD-17350       Maribeth Dona    3766.3820     -241.9500
27    CS-12400  Christopher Schild    3651.8585     -342.8033
28    DL-13495        Dionis Lloyd    3539.3220      -52.7880
29    AG-10675         Anna Gayman    3489.0396     -246.4257
30    SC-20020          Sam Craven    3362.9636     -317.0508
31    VP-21760    Victoria Pisteka    3360.5260    -1018.7768
32    DC-12850        Dan Campbell    3336.1680    -1441.6313
33    HG-14965       Henry Goldwyn    3247.6420    -2797.9635
34    EB-13750       Edward Becker    3236.3140      -80.2860
35    SR-20425      Sharelle Roach    3233.4810    -3333.9144
36    TN-21040       Tanja Norvell    3130.2210     -692.0452
37    MG-18145     Mike Gockenbach    3061.5430      -93.6030
38    SS-20410     Shahid Shariari    3056.8070    -1010.9738
39    AS-10045      Aaron Smayling    3050.6920     -253.5746
40    CS-11950      Carlos Soltero    3036.5470     -126.4223
41    DB-13120        David Bremer    2973.0940    -1421.7692
42    NS-18640        Noel Staavos    2964.8230     -234.7714
43    TH-21115       Thea Hudgings    2942.7720     -252.5539
44    ML-17410        Maris LaWare    2921.5000      -76.1755

In [90]:
import sys
from pathlib import Path

project_root = Path.cwd().parent

if str(project_root) not in sys.path:
    sys.path.append(str(project_root))

from scripts.database_utils import run_query

In [91]:
run_query("""
SELECT name, type
FROM sqlite_master
WHERE type IN ('table', 'view');
""")

                     name   type
0               customers  table
1                products  table
2  customer_sales_summary   view
3                   sales  table

In [92]:
query = """
SELECT
    "Category",
    SUM("Sales") AS total_sales,
    SUM("Profit") AS total_profit
FROM sales
GROUP BY "Category"
ORDER BY total_sales DESC;
"""

result = run_query(query)

result

          Category  total_sales  total_profit
0       Technology  839893.2790   146543.3756
1        Furniture  754747.7613    19729.9956
2  Office Supplies  731893.3140   126023.4434